### ISSUE TITLE
Error with Train Progress

### ISSUE THREAD

**Issue by givenchyhuang** [i-sultan/Smart-Trader#1]
Hi ,

I followed the step wrote in README.
In Train step , I entered the Stock AAPL , Start Date 2010-01-01 , End Date 2016-01-01 , Model KNN
, then I got the python error message 

==== error message ======

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1537, in **call**
    return self.func(*args)
  File "/Users/Smart-Trader/src/st_train_view.py", line 68, in <lambda>
    command=lambda: start_training())
  File "/Users/Smart-Trader/src/st_train_view.py", line 103, in start_training
    training_summary_file = self.controller.run_training(training_id, symbol, start_date, end_date, update_progress)
  File "/Users/Smart-Trader/src/st_train_controller.py", line 50, in run_training
    df = get_data_web(symbol, dates, False)
  File "/Users/Smart-Trader/src/st_helpers.py", line 86, in get_data_web
    df['SMA'] = df[symbol].pct_change(periods=1).rolling(window = 10).mean()
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 2246, in **getattr**
    (type(self).**name**, name))
AttributeError: 'Series' object has no attribute 'rolling'
# 

How do I solve the problem ?

**Comment by i-sultan** [comment]
Thanks for the report, please make sure to update your pandas to version 0.18.0 or later. 

According to: http://pandas.pydata.org/pandas-docs/stable/computation.html

> Warning: Prior to version 0.18.0, pd.rolling__, pd.expanding__, and pd.ewm\* were module level functions and are now deprecated. These are replaced by using the Rolling, Expanding and EWM. objects and a corresponding method call.
